- hosts: all
  become: true
  pre_tasks:
    - name: Debug all variables
      debug:
        msg: "{{ hostvars[inventory_hostname] }}"
  roles:
    - role: common
    - role: docker
    - role: pterodactyl_panel
    - role: pterodactyl_wings
    - role: nginx
    - role: ssl
