- hosts: all
  become: true
  pre_tasks:
    - name: Debug firewall_allowed_ports
      debug:
        var: firewall_allowed_ports
  roles:
    - role: common
    - role: docker
    - role: pterodactyl_panel
    - role: pterodactyl_wings
    - role: nginx
    - role: ssl
